### PR TITLE
修复一些问题

### PR DESCRIPTION
**Pull request by a632079**
由于没有QQ互联的接口（目前需要备案），我无法完成整个测试。。。请大家如果在使用过程中碰到问题了，务必私聊我（明天看看依赖包是否需要我进行更新）

### CODE REVIEW

**Comment by a632079** [comment]
@julianlam I can't solve the problem that "[plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
  * nodebb-plugin-sso-qq-fix
".
Could you help me solve it?
The Program is in [this](https://github.com/NodeBB-China/nodebb-plugin-sso-qq-fix)

**Comment by julianlam** [comment]
If the plugin _is_ compatible, then just modify the nbbpm.compatibility value in package.json

**Comment by a632079** [comment]
@julianlam Thanks a lot.

**Comment by a632079** [comment]
等待修复 #2

**Comment by a632079** [comment]
由于项目无人维护，所以另开项目并关闭Pull Request

**Pull request closed without merging**
